ENG-3975 Return bytes instead of str for py3 compatibility
2hat/tornado-botocore pull request #1
Opened 2020-04-03 23:27 UTC by blee2hat

Ticket: ENG-3975

#### Changes proposed:
Modified to use bytes instead of str when hardcoding response_dict['body']

#### Justification for inclusion in release:
- Prioritized item in sprint
- Production issue due to Python 3 upgrade

#### Deployment instructions:
N/A

2020-04-03 23:44 UTC, michaelwhenderson requested changes
We need to bump up the version number to something like 1.5.1 in __init__.py so that pip understands which version is installed.

The rest looks good though

2020-04-04 00:30 UTC, blee2hat commented
I changed version to `1.5.0.1` in case there is `1.5.1` from upstream.

2020-04-04 00:41 UTC, michaelwhenderson approved these changes

2020-04-04 02:13 UTC, merged

2020-04-06 17:51 UTC, pandasuit commented
i was going to suggest we try pushing our changes to the upstream repo then i noticed that repo hasn't had changes in years and is probably dead. @michaelwhenderson any major concerns about the near term use of this library being a problem if it's not getting updates? most of the functionality is still handled by botocore itself and that is still getting security patches as of a few months ago.

2020-04-06 17:54 UTC, michaelwhenderson commented
This library is mostly just an asynchronous wrapper around botocore so it shouldn't be a high risk.  We can looks for something else to replace it if you think it is a concern.

2020-04-06 17:55 UTC, michaelwhenderson commented
We may want to move this functionality into a brokered service anyway